apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf-reserved-resources-recommender
  labels:
    name: prometheus-server-conf
#  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'reserved-resources-recommender'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'reserved-resources-recommender'
          action: keep
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: instance