---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-web-reserved-resources-recommender
#  namespace: monitoring
spec:
  ports:
    - port: 9090
      protocol: TCP
  selector:
    app: prometheus-server
  sessionAffinity: None
  type: ClusterIP