apiVersion: v1
kind: Service
metadata:
  labels:
    component: better-resource-reservations
  name: better-resource-reservations
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 16911
      protocol: TCP
      targetPort: 16911
  selector:
    component: better-resource-reservations
  sessionAffinity: None
  type: ClusterIP
