apiVersion: v1
kind: Service
metadata:
  labels:
    component: reserved-resources-recommender
  name: reserved-resources-recommender
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 16911
      protocol: TCP
      targetPort: 16911
  selector:
    component: reserved-resources-recommender
  sessionAffinity: None
  type: ClusterIP
