# see the documentation at: https://chaos-mesh.org/docs/simulate-heavy-stress-on-kubernetes/
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress
  namespace: stress
spec:
  mode: all
  selector:
    labelSelectors:
      stress: me
  containerNames:
    - dummy
  stressors:
    cpu:
      workers: 6
      load: 50
  duration: "5h"
