# will be injected by chaos mesh
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stresstest
  namespace: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      stress: me
  template:
    metadata:
      labels:
        stress: me
    spec:
      containers:
        - command:
            - sleep
            - "1000000000"
          image: eu.gcr.io/gardener-project/gardener/ops-toolbelt
          imagePullPolicy: Always
          name: dummy
          resources: { }
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      priority: 0
      nodeName: ip-10-180-0-64.eu-west-1.compute.internal
      restartPolicy: Always

