apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy-pod
  namespace: kube-system
spec:
  nodeName: lima-docker
  automountServiceAccountToken: false
  containers:
    - command:
        - /usr/local/bin/kube-proxy
        - --config=/var/lib/kube-proxy-config/config.yaml
        - --v=2
#      env:
#        - name: KUBERNETES_SERVICE_HOST
#          value: api.aws-clone.dev.internal.dev.k8s.ondemand.com
      image: k8s.gcr.io/kube-proxy:v1.21.2
      imagePullPolicy: IfNotPresent
      name: kube-proxy
      ports:
        - containerPort: 10249
          hostPort: 10249
          name: metrics
          protocol: TCP
      resources:
        limits:
          cpu: 44m
          memory: "145014992"
        requests:
          cpu: 11m
          memory: "36253748"
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/kube-proxy-kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /var/lib/kube-proxy-config
          name: kube-proxy-config
        - mountPath: /etc/ssl/certs
          name: ssl-certs-hosts
          readOnly: true
        - mountPath: /var/run/dbus/system_bus_socket
          name: systembussocket
        - mountPath: /lib/modules
          name: kernel-modules
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/disk-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/pid-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/network-unavailable
      operator: Exists
  volumes:
#    - name: kubeconfig
#      secret:
#        defaultMode: 420
#        secretName: kube-proxy  #
    - name: kubeconfig
      hostPath:
        path: "/Users/d060239/go/src/github.com/gardener/gardener/hack/local-development/local-garden/kubeconfigs" # Just use admin config for my local -dev
        type: "Directory"
    - configMap:
        defaultMode: 420
        name: kube-proxy-config # TO BE CREATED
      name: kube-proxy-config
    - hostPath:
        path: /usr/share/ca-certificates
        type: ""
      name: ssl-certs-hosts
    - hostPath:
        path: /var/run/dbus/system_bus_socket
        type: ""
      name: systembussocket
    - hostPath:
        path: /lib/modules
        type: ""
      name: kernel-modules
    - hostPath:
        path: /var/lib/kube-proxy
        type: DirectoryOrCreate
      name: kube-proxy-dir
    - hostPath:
        path: /var/lib/kube-proxy/mode
        type: FileOrCreate
      name: kube-proxy-mode