apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy-config
  namespace: kube-system
data:
  # clusterCIDR: 100.96.0.0/11 # clusterCIDR is the pod CIDR
  config.yaml: |-
    ---
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    clientConnection:
      kubeconfig: /var/lib/kube-proxy-kubeconfig/default-admin.conf
    metricsBindAddress: 0.0.0.0:10249
    mode: iptables
    conntrack:
      maxPerCore: 524288

