#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: grafana-pvc
##  namespace: monitoring
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-reserved-resources-recommender
  name: grafana-reserved-resources-recommender
#  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana-reserved-resources-recommender
  template:
    metadata:
      labels:
        app: grafana-reserved-resources-recommender
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 1
      containers:
        - name: grafana
          image: grafana/grafana:8.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/grafana-storage
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              # path as configured in grafana-dashboard-providers
            - mountPath: /var/lib/grafana/dashboards
              name: grafana-dashboards
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboard-providers

      volumes:
        - name: grafana-storage
          emptyDir: {}
        - configMap:
            defaultMode: 420
            name: grafana-dashboards-reserved-resources-recommender
          name: grafana-dashboards
        - configMap:
            defaultMode: 420
            name: grafana-datasources-reserved-resources-recommender
          name: grafana-datasources
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-providers-reserved-resources-recommender
          name: grafana-dashboard-providers