---
apiVersion: v1
kind: Service
metadata:
  name: grafana-reserved-resources-recommender
#  namespace: monitoring
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana-reserved-resources-recommender
  sessionAffinity: None
  type: ClusterIP