apiVersion: v1
data:
  datasources.yaml: |-
    # config file version
    apiVersion: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: prometheus-web-reserved-resources-recommender:9090
      basicAuth: false
      isDefault: true
      version: 1
      editable: false
      jsonData:
        timeInterval: 10s
        httpMethod: POST
kind: ConfigMap
metadata:
  name: grafana-datasources-reserved-resources-recommender
#  namespace: monitoring
