apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: gardener.privileged
  labels:
    app: root
    component: better-resource-reservations
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-shoot-apiserver: allowed
  name: better-resource-reservations
spec:
  containers:
    - image: eu.gcr.io/gardener-project/gardener/better-resource-reservations:latest
      imagePullPolicy: Always
      name: reconciler
      env:
        - name: ENFORCE_RECOMMENDATION
          value: "false"
        - name: MIN_DELTA_ABSOLUTE
          value: 2Mi
        - name: MIN_THRESHOLD_PERCENT
#          0.2 means that it only starts working when available memory < 20 %
          value: "0.9"
        - name: KUBELET_CONFIG_PATH
          value: "/Users/d060239/go/src/github.com/danielfoehrkn/better-resource-reservations/example/kubelet/config"
      resources:
        requests:
          memory: "16Mi"
          cpu: "20m"
        limits:
          memory: "30Mi"
          cpu: "40m"
      securityContext:
        privileged: true
        runAsUser: 0
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /run/systemd/private
          name: systemd
        - mountPath: /proc/meminfo
          name: proc
        - mountPath: /var/lib/kubelet/config/kubelet
          name: kubelet-config
        - mountPath: /var/lib/kubelet/dynamic-resource-reservations/kubelet.sock
          name: kubelet-dynamic-resource-reservations-socket
        - mountPath: /sys/fs/cgroup
          name: cgroup-hierarchy
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  nodeName: lima-docker
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: pool.worker.gardener.cloud/dedicated-for
      operator: Equal
      value: etcd
  volumes:
    - hostPath:
        path: /run/systemd/private
        type: ""
      name: systemd
    - hostPath:
        path: /proc/meminfo
        type: ""
      name: proc
    - hostPath:
        path: /var/lib/kubelet/config/kubelet
        type: ""
      name: kubelet-config
    - hostPath:
        path: /var/lib/kubelet/dynamic-resource-reservations/kubelet.sock
        type: "File"
      name: kubelet-dynamic-resource-reservations-socket
    - hostPath:
        path: /sys/fs/cgroup
        type: ""
      name: cgroup-hierarchy

