apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir-example
spec:
  nodeName: shoot--d060239--dev-seed-gcp-cpu-worker-z1-66bf7-xjzzn
  containers:
    - name: test-webserver
      image: k8s.gcr.io/test-webserver:latest
      volumeMounts:
        - mountPath: /cache
          name: cache-volume-normal
  volumes:
    - name: cache-volume-normal
      emptyDir: {}