apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-leak
spec:
  replicas: 0
  selector:
    matchLabels:
      loadtest: memory
  template:
    metadata:
      labels:
        loadtest: memory
    spec:
      containers:
        - image: stephanlindauer/docker-memory-leak
          imagePullPolicy: IfNotPresent
          name: dummy
          resources: { }
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      priority: 0
      nodeName: ip-10-240-24-238.eu-central-1.compute.internal
      restartPolicy: Always

