apiVersion: v1
kind: Pod
metadata:
  name: podload
  generateName: podload
spec:
  containers:
    - command:
        - sleep
        - "10000000"
      image: eu.gcr.io/gardener-project/gardener/ops-toolbelt
      imagePullPolicy: Always
      name: dummy
      resources: {}
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  nodeName: lima-docker
  priority: 0
  restartPolicy: Always

